<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Murillo">

<title>Inferencia estadística</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Clase2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Clase2_files/libs/quarto-html/quarto.js"></script>
<script src="Clase2_files/libs/quarto-html/popper.min.js"></script>
<script src="Clase2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Clase2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Clase2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Clase2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Clase2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Clase2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Clase2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Inferencia estadística</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Murillo </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="estimación-de-parámetros" class="level3">
<h3 class="anchored" data-anchor-id="estimación-de-parámetros">Estimación de parámetros</h3>
<p><em>El propósito principal de la inferencia estadística</em></p>
<p>La inferencia estadística tiene como objetivo estimar los valores de los parámetros (desconocidos) en un modelo estadístico. Todo modelo estadístico es una construcción teórica formulada como una ecuación matemática que podría generar los datos observados para alguna combinación de sus parámetros y de los valores de las variables explicativas. Estimar los valores de los parámetros del modelo permite utilizar el modelo estadístico como un mecanismo generador de datos, cuyas predicciones pueden compararse con la evidencia disponible.</p>
<p>El objetivo de la estadística rara vez es llegar a conclusiones o hacer afirmaciones sobre los datos específicos que se tienen a mano. Más bien, estos se consideran un pequeño subconjunto obtenido de una colección mucho más amplia de valores potenciales de las variables de respuesta y explicativas que podrían haberse registrado para el mismo proceso hipotético generador de datos. La población estadística se define como el conjunto completo de valores de la variable de respuesta que podrían incluirse en una muestra. La información contenida en una muestra (desde el punto de vista de la inferencia estadística, las estimaciones de los parámetros) no es más que un medio transitorio para alcanzar el objetivo mayor de obtener conclusiones confiables sobre la población estadística. En otras palabras, la estimación estadística trata típicamente sobre el proceso que se piensa generó los datos observados o, de manera equivalente, sobre “todos” los conjuntos de datos que dicho proceso podría haber producido.</p>
<p>Referencia principal de la clase: <a href="https://doi.org/10.1093/oso/9780192859013.003.0003">Statistical Modeling with R: CHAPTER 3 Estimating Parameters: The main purpose of statistical inference</a></p>
</section>
<section id="métodos-de-estimación-de-parámetros" class="level2">
<h2 class="anchored" data-anchor-id="métodos-de-estimación-de-parámetros">Métodos de estimación de parámetros</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Mínimos cuadrados</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Máxima verosimilitud</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Estimación bayesiana de parámetros</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">Pruebas de hipótesis</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p><em>Una teoría de los errores y la distribución normal</em></p>
<p>El primer enfoque para la estimación de parámetros puede encontrarse en el artículo de Bayes (1763). Fue desarrollado de manera independiente y sustancial por Laplace (1814) hasta convertirse en lo que hoy llamamos métodos bayesianos. Tanto Bayes como Laplace utilizaron la probabilidad inversa, mediante el ahora estándar teorema de Bayes, para estimar los parámetros de un modelo estadístico a partir de los datos. El método Bayes-Laplace fue el único método disponible de inferencia estadística hasta que Gauss desarrolló el método de mínimos cuadrados en 1809, en conexión con la distribución normal. Así, generó una teoría de los errores al ajustar curvas y superficies a mediciones en geodesia y astronomía. En 1814, Laplace demostró el primer teorema central del límite, según el cual la composición aditiva de variables aleatorias independientes e idénticamente distribuidas sigue una distribución normal. De esta manera, justificó el uso del método de mínimos cuadrados para tamaños de muestra grandes. El siglo XIX presenció la creciente recopilación de grandes conjuntos de datos en las ciencias sociales y naturales, lo que llevó al desarrollo de métodos analíticos como la regresión lineal y la correlación. El método de mínimos cuadrados desempeñó un papel importante en el análisis de esos grandes conjuntos de datos de variables cuantitativas que podían asumirse como normalmente distribuidas.</p>
<p>El método de mínimos cuadrados es un método de estimación de parámetros en modelos lineales en el que la variable de respuesta sigue una distribución normal con varianza constante (esto se conoce como homocedasticidad). Sin embargo, muchas variables de respuesta no siguen una distribución normal, ni pueden transformarse para cumplirla. Por lo tanto, el método de mínimos cuadrados solo puede utilizarse en un conjunto relativamente limitado de circunstancias.</p>
<p>La estimación por mínimos cuadrados (Least Squares) busca encontrar los parámetros de un modelo que minimicen la suma de los errores al cuadrado entre los valores observados y los valores predichos por el modelo.</p>
<p>Modelo lineal simple:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_1 + \varepsilon_i\]</span> Donde:</p>
<p><span class="math inline">\(y_i\)</span>: valor observado de la variable respuesta en la observación <em>i</em><br>
<span class="math inline">\(x_i\)</span>: valor de la variable explicativa en la observación <em>i</em><br>
<span class="math inline">\(\beta_0\)</span>: intercepto del modelo<br>
<span class="math inline">\(\beta_1\)</span>: coeficiente de regresión (pendiente)<br>
<span class="math inline">\(\varepsilon_i\)</span>: término de error aleatorio asociado a la observación <em>i</em></p>
<p>¿Qué hace mínimos cuadrados?</p>
<p><a href="https://myz303.com/linear_regression_en.html">Mathematical Derivation of Linear Regression Coefficients</a></p>
<p><a href="https://doi.org/10.1117/12.2628017">Statistical derivation of linear regression</a></p>
<p>Busca los valores <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> que minimicen la suma de los errores al cuadrado (SSE, por sus siglas en inglés):</p>
<p><span class="math display">\[\sum_{i=1}^{n} (y_i - \hat{y}_i)^2\]</span></p>
<p><span class="math inline">\(y_i\)</span>: valor observado de a variable respuesta</p>
<p><span class="math inline">\(\hat{y}_i\)</span>: valor estimado o predicho por el modelo</p>
<p>Solución (modelo lineal simple)</p>
<p>Pendiente:</p>
<p><span class="math display">\[\beta_1 = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2}\]</span> Intercepto:</p>
<p><span class="math display">\[\beta_0 = \bar{y} - \beta_1\bar{x}\]</span></p>
<p><span class="math inline">\(\bar{x}\)</span>: Media muestral de la variable <em>x</em></p>
<p><span class="math inline">\(\bar{y}\)</span>: Media muestral de la variable <em>y</em></p>
<section id="ejercicio" class="level4">
<h4 class="anchored" data-anchor-id="ejercicio">Ejercicio</h4>
<p>Es momento de aplicar el método de mínimos cuadrados utilizando una base de datos recopilada por el Dr.&nbsp;McGarigal durante su doctorado en el noroeste del Pacífico. Esta base de datos contiene información sobre la abundancia de Certhia americana (trepador americano) y diversas variables predictoras.</p>
<ul>
<li>abund: abundancia de Certhia americana</li>
<li>elevation: elevación promedio del sitio</li>
<li>road.dens: densidad de carreteras en el sitio</li>
<li>stream.den: densidad de arroyos en el sitio</li>
<li>mps.CS: tamaño medio de parche en el sitio, donde el tamaño del parche se define por la composición y estructura de la vegetación</li>
<li>mps.S: tamaño medio de parche en el sitio, donde el tamaño del parche se define únicamente por la estructura de la vegetación</li>
<li>contagion: medida de la agregación (o “agrupamiento”) del mosaico de parches, donde los parches se definieron a partir de mps.S</li>
<li>conifer: porcentaje del paisaje compuesto por bosque de coníferas</li>
<li>saw: porcentaje del paisaje compuesto por rodales de madera madura (fase tardía de sucesión)</li>
<li>pole: porcentaje del paisaje compuesto por rodales en etapa intermedia de sucesión</li>
<li>sapling: porcentaje del paisaje compuesto por rodales jóvenes (fase temprana de sucesión)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>CerthiaAmericana <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">"data/creeps.txt"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> CerthiaAmericana<span class="sc">$</span>conifer</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> CerthiaAmericana<span class="sc">$</span>abund</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Promedios</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>x_media <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>y_media <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Pendiente (beta1)</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">sum</span>((x <span class="sc">-</span> x_media) <span class="sc">*</span> (y <span class="sc">-</span> y_media)) <span class="sc">/</span> <span class="fu">sum</span>((x <span class="sc">-</span> x_media)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Intercepto (beta0)</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> y_media <span class="sc">-</span> beta1 <span class="sc">*</span> x_media</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores predichos</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> x</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuales</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> y <span class="sc">-</span> y_hat</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># SSE (suma de cuadrados del error)</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>(residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar resultados</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>beta0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.409713</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>beta1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0003403028</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>SSE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.454339</code></pre>
</div>
</div>
<p>Una vez que hemos calculado correctamente el intercepto y la pendiente, procederemos a validar nuestros resultados comparándolos con los obtenidos mediante un modelo lineal.</p>
<p>El modelo lineal, específicamente la regresión lineal, utiliza el método de mínimos cuadrados para estimar los parámetros del modelo (la pendiente y el intercepto).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.38821 -0.14525 -0.03574  0.17354  0.57945 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.4097130  0.1095886   3.739 0.000843 ***
x           -0.0003403  0.0019764  -0.172 0.864533    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2279 on 28 degrees of freedom
Multiple R-squared:  0.001058,  Adjusted R-squared:  -0.03462 
F-statistic: 0.02965 on 1 and 28 DF,  p-value: 0.8645</code></pre>
</div>
</div>
</section>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Este es un método general para la estimación de parámetros en modelos estadísticos, creado de manera independiente por R. A. Fisher entre 1912 y 1922. El método de máxima verosimilitud puede estimar los valores de los parámetros del modelo para cualquier distribución de probabilidad utilizada para describir una variable de respuesta. La máxima verosimilitud se convirtió en una herramienta esencial de propósito general en la inferencia estadística frecuentista, ya que permite evaluar la significancia estadística, calcular intervalos de confianza, realizar la evaluación y comparación de modelos, y hacer predicciones. Es importante destacar que los estimadores de máxima verosimilitud para una variable de respuesta normal coinciden con los correspondientes estimadores de mínimos cuadrados.</p>
<p>Los estimadores de máxima verosimilitud de los parámetros de un modelo se obtienen al maximizar la función de verosimilitud con respecto a sus parámetros. Esto produce los valores de los parámetros que tienen mayor probabilidad de haber generado los datos observados, dado la Función de masa de probabilidad (PMF) o Función de densidad de probabilidad (PDF) utilizada para modelar la variable de respuesta. Por lo tanto, la función de verosimilitud ni surge de la nada ni su definición requiere inspiración divina. Más bien, está definida por la función de densidad de probabilidad o de masa de probabilidad de la variable de respuesta en el modelo estadístico.</p>
<p>Entonces, ¿cómo podemos obtener los valores de los parámetros que maximizan esa función? En algunos casos, los estimadores de máxima verosimilitud de los parámetros del modelo pueden obtenerse calculando analíticamente la derivada de la función de verosimilitud con respecto a sus parámetros, y luego igualándola a cero para determinar su máximo. Cuando hacemos esto, obtenemos fórmulas simples que nos permiten obtener directamente los estimadores de máxima verosimilitud a partir de los datos. En otros casos, maximizar la función de verosimilitud se logra mediante métodos numéricos, muchos de los cuales han sido implementados en R.</p>
<p>Nota: <em>En el análisis de datos ecológicos, es fundamental seleccionar la distribución de probabilidad adecuada según la naturaleza de la variable de respuesta. Por ejemplo, los conteos de aves suelen modelarse mediante una función de masa de probabilidad (PMF) bajo una distribución de Poisson, implementada en R con dpois(). De manera similar, los datos de presencia/ausencia se describen mediante una PMF con distribución binomial, utilizando dbinom(). En contraste, las variables continuas, como medidas de biomasa o peso, se modelan mediante una función de densidad de probabilidad (PDF) bajo una distribución normal, implementada en R con dnorm().</em></p>
<p>Conteos de aves → PMF (Poisson) → dpois()</p>
<p>Presencia/ausencia → PMF (Binomial) → dbinom()</p>
<p>Variables continuas → PDF (Normal) → dnorm()</p>
<section id="ejercicio-1" class="level4">
<h4 class="anchored" data-anchor-id="ejercicio-1">Ejercicio</h4>
<p>Para este ejercicio, se utilizará la misma base de datos de Certhia americana empleada en el ejercicio de mínimos cuadrados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> CerthiaAmericana<span class="sc">$</span>abund</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> CerthiaAmericana<span class="sc">$</span>conifer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El gráfico generado con geom_density() muestra la distribución de la variable abund a partir de los datos observados, proporcionando una estimación suavizada de la densidad. En este caso, la forma de la curva refleja cómo se distribuyen los valores en el conjunto de datos, indicando en qué rangos se concentran con mayor frecuencia. Las áreas donde la curva es más alta representan valores más comunes, mientras que las zonas donde la curva se acerca a cero indican valores menos frecuentes. Este tipo de gráfico permite identificar patrones en la distribución de los datos, como asimetrías, multimodalidad o concentración de valores, sin asumir previamente una forma específica de distribución, a diferencia de un modelo paramétrico como el definido por dnorm().</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> CerthiaAmericana, <span class="fu">aes</span>(<span class="at">x=</span> abund))<span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>()<span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Clase2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Secuencia de valores para evaluar la densidad</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(y), <span class="fu">max</span>(y), <span class="at">length =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Densidad usando dnorm</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>densidad <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="fl">0.39</span>, <span class="at">sd =</span> <span class="fl">0.22</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, densidad, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"abund"</span>, <span class="at">ylab =</span> <span class="st">"Densidad"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Densidad teórica usando dnorm()"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Clase2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico generado representa la densidad teórica de una distribución normal calculada con la función dnorm(), utilizando una media de 0.39 y una desviación estándar de 0.22.</p>
<p>En el eje x se muestran los posibles valores de la variable abund, definidos a través del vector x, el cual contiene una secuencia continua de valores dentro del rango observado. En el eje y se presenta la densidad de probabilidad, que indica qué tan probable es cada valor de abund bajo el modelo normal especificado.</p>
<p>La curva obtenida tiene forma de campana (curva gaussiana), característica de la distribución normal. El punto más alto de la curva corresponde a la media (0.39), donde se concentra la mayor densidad, lo que indica que los valores cercanos a 0.39 son los más probables bajo este modelo. A medida que los valores se alejan de la media hacia ambos lados, la densidad disminuye gradualmente, reflejando que los valores extremos son menos probables.</p>
<p>El método de máxima verosimilitud busca identificar los valores de los parámetros que hacen más probable observar los datos dados bajo un modelo estadístico. En este caso, se evalúa la verosimilitud de diferentes valores de la media (0.4, 0.01 y 1) utilizando la función dnorm(), que calcula la densidad de probabilidad para cada observación bajo una distribución normal. Como los datos se asumen independientes, las probabilidades individuales se combinan mediante una multiplicación; sin embargo, debido a problemas numéricos y de interpretación, se utiliza el logaritmo de la verosimilitud, lo que transforma la multiplicación en una suma, facilitando el cálculo y evitando valores extremadamente pequeños. Por esta razón, se usa log = TRUE y luego se suman los valores con sum(). El valor de verosimilitud resultante indica qué tan bien cada valor de la media explica los datos: el modelo con el mayor valor (más cercano a cero o positivo, como 2.797019 en el caso de 0.4) es el que mejor ajusta los datos, mientras que valores más negativos (como -42.46961 para 0.01) indican un peor ajuste. De esta forma, el método de máxima verosimilitud permite comparar distintos parámetros y seleccionar aquel que maximiza la probabilidad de los datos observados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dnorm</span>(y, <span class="at">mean =</span> <span class="fl">0.4</span>, <span class="at">sd =</span> <span class="fl">0.22</span>, <span class="at">log =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.797019</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dnorm</span>(y, <span class="at">mean =</span> <span class="fl">0.01</span>, <span class="at">sd =</span> <span class="fl">0.22</span>, <span class="at">log =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -42.46961</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dnorm</span>(y, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="fl">0.22</span>, <span class="at">log =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -111.6529</code></pre>
</div>
</div>
<p>A continuación, se aplicará el método de máxima verosimilitud para encontrar el intercepto y la pendiente más apropiados que permitan explicar la relación entre la abundancia de Certhia americana y el porcentaje de bosque de coníferas. En este ejercicio, se explorarán diferentes combinaciones de parámetros dentro de un modelo lineal y se calculará la verosimilitud para cada una, con el objetivo de identificar los valores que maximicen la probabilidad de observar los datos. De esta manera, se seleccionarán el intercepto y la pendiente que mejor describan el patrón presente en los datos, permitiendo interpretar cómo cambia la abundancia de la especie en función de la cobertura de bosque de coníferas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> CerthiaAmericana<span class="sc">$</span>abund</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> CerthiaAmericana<span class="sc">$</span>conifer</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>beta0_vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="fl">0.8</span>, <span class="at">length.out =</span> <span class="dv">100</span>)  </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>beta1_vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.001</span>, <span class="fl">0.001</span>, <span class="at">length.out =</span> <span class="dv">10</span>)  </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">sd</span>(y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Evaluar cada combinación paso a paso</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (b0 <span class="cf">in</span> beta0_vals) {</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (b1 <span class="cf">in</span> beta1_vals) {</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    logLik <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">dnorm</span>(y, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma, <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    results <span class="ot">&lt;-</span> <span class="fu">rbind</span>(results, <span class="fu">data.frame</span>(<span class="at">beta0 =</span> b0,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">beta1 =</span> b1,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">logLik =</span> logLik))</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Identificar el mejor modelo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>results[<span class="fu">which.max</span>(results<span class="sc">$</span>logLik), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        beta0         beta1  logLik
444 0.4111111 -0.0003333333 2.82154</code></pre>
</div>
</div>
<p>Los resultados indican que el modelo con <span class="math inline">\(\beta_0\)</span> = 0.411 y <span class="math inline">\(\beta_1\)</span> = -0.00031 presenta el valor de log-verosimilitud más alto (2.82154) entre las combinaciones evaluadas, lo que sugiere que esta combinación de parámetros es la que mejor explica los datos bajo el modelo asumido. En este caso, el intercepto cercano a 0.41 representa el valor esperado de la variable respuesta cuando el predictor es cero, mientras que la pendiente negativa indica que existe una relación inversa entre la variable explicativa y la respuesta, es decir, a medida que aumenta el predictor, la variable respuesta tiende a disminuir. El valor relativamente alto de la log-verosimilitud indica un buen ajuste del modelo a los datos, en comparación con otras combinaciones evaluadas.</p>
</section>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p>La estadística bayesiana se fundamenta en el teorema de Bayes, el cual establece la relación entre probabilidades condicionadas mediante la expresión: Pr(A|B) × Pr(B) = Pr(B|A) × Pr(A). Este enfoque parte de una creencia inicial sobre un parámetro o evento, conocida como prior, la cual representa el conocimiento previo antes de observar los datos. Posteriormente, esta creencia se actualiza mediante la incorporación de nueva evidencia proveniente de los datos observados, conocida como verosimilitud. El resultado de esta combinación es la probabilidad posterior, que representa la nueva estimación del parámetro después de considerar la información disponible. Por ejemplo, al estimar la presencia de una especie en un área determinada, se puede asignar inicialmente una probabilidad basada en conocimiento previo; luego, al observar datos de campo, esta probabilidad se actualiza para reflejar de manera más precisa la evidencia empírica. De esta forma, la estadística bayesiana permite integrar el conocimiento previo con la información nueva para mejorar la inferencia y la toma de decisiones.</p>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Concepto de hipótesis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Valor P</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Intervalos de confianza</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Error tipo I y II</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href="">Poder estadístico</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Referencia: <a href="https://www.cabidigitallibrary.org/doi/full/10.5555/19712702614">Shork. M and Remington, R. (1970).</a></p>
<p>En muchos estudios, el investigador busca comparar sus datos con un valor de referencia. Este valor puede corresponder a un parámetro poblacional específico, o bien a la diferencia o proporción entre parámetros de dos poblaciones.</p>
<p>Por ejemplo, en un estudio taxonómico, se podrían comparar las longitudes de larvas provenientes de dos poblaciones de insectos para evaluar si ambas tienen la misma media. En este contexto, el investigador se plantea si la diferencia entre las medias poblacionales podría ser igual a cero. A partir de ello, los datos se analizan para determinar si son compatibles o no con esta idea.</p>
<p>Con base en ese análisis, se toma una decisión: aceptar o rechazar la posibilidad de que no exista diferencia entre las poblaciones. Dependiendo del resultado, esto puede orientar diferentes caminos en la investigación, como ajustar la clasificación de las especies.</p>
<p>Desde la perspectiva estadística, lo fundamental es que el investigador utiliza información muestral para evaluar una afirmación sobre una o más poblaciones. A este proceso se le conoce como prueba de hipótesis.</p>
<p>Dado que las pruebas de hipótesis se basan en muestras y no en la población completa, siempre existe la posibilidad de cometer errores en la inferencia. En este contexto, se distinguen dos tipos principales de error. El error de Tipo I ocurre cuando se rechaza una hipótesis nula que en realidad es verdadera, y su probabilidad está determinada por el nivel de significancia (α). Por otro lado, el error de Tipo II ocurre cuando no se rechaza una hipótesis nula que es falsa. Este error está relacionado con el poder estadístico de la prueba, definido como la probabilidad de detectar un efecto real cuando este existe (1 − <span class="math inline">\(\beta\)</span>).</p>
<p><strong>Definiciones</strong></p>
<p><em>Hipótesis estadística</em>: Una afirmación sobre la población o poblaciones que se están muestreando, u ocasionalmente una afirmación sobre el procedimiento de muestreo. Por ejemplo, esta moneda cae cara, esta moneda cae cruz, este fármaco es superior al placebo, este fármaco no es diferente al placebo.</p>
<p><em>Hipótesis contrastada o nula</em>: Una hipótesis estadística cuya veracidad se investiga mediante el muestreo; a veces se denomina hipótesis nula o, cuando no hay peligro de ambigüedad, simplemente hipótesis. Por ejemplo, esta moneda cae cara, este fármaco no es diferente al placebo.</p>
<p><em>Prueba Estadística</em>: Una variable aleatoria relacionada con la hipótesis contrastada. Por ejemplo, el número total de caras al lanzar una moneda 10 veces, o la diferencia entre la reducción porcentual media del colesterol sérico para el fármaco en comparación con el placebo.</p>
<p><em>Región crítica</em>: Un conjunto de valores del estadístico de prueba que lleva al rechazo de la hipótesis contrastada; a veces se denomina región de rechazo. Por ejemplo, 0, 1, 9 o 10 caras, o una diferencia porcentual igual a 5.</p>
<p><em>Valor significativo de la Prueba Estadística</em>: Un valor de la Prueba Estadística que cae dentro de la región crítica; generalmente, cuando una muestra produce un valor de la Prueba Estadística en la región crítica, se dice que los resultados son estadísticamente significativos. Por ejemplo, cualquier número total de caras de 1 o menos, o de 9 o más; una reducción porcentual de 5.</p>
<p><em>Región de aceptación</em>: Un conjunto de valores de la Prueba Estadística que lleva a la aceptación de la hipótesis contrastada, es decir, los valores de la Prueba Estadística no incluidos en la región crítica. Por ejemplo, 2, 3, 4, 5, 6, 7 u 8 caras; cualquier porcentaje excepto el 5.</p>
<p><em>Prueba de hipótesis</em>: Un procedimiento mediante el cual se investiga la veracidad o falsedad de la hipótesis contrastada examinando un valor de la Prueba Estadística calculado a partir de una muestra, y luego se decide rechazar o aceptar la hipótesis según si el valor cae en la región crítica o en la región de aceptación, respectivamente.</p>
<p><em>Error de tipo I</em>: El error de rechazar la hipótesis contrastada cuando en realidad es verdadera; a veces se denomina error <span class="math inline">\(\alpha\)</span>.</p>
<p><em>Error de tipo II</em>: El error de aceptar la hipótesis contrastada cuando en realidad es falsa; a veces se denomina error <span class="math inline">\(\beta\)</span>.</p>
<p><em>Nivel de significancia</em>: La probabilidad de cometer un error de tipo I; se denota como <span class="math inline">\(\alpha\)</span>.</p>
<p><em>Hipótesis alternativa</em>: Una hipótesis estadística que discrepa de la hipótesis nula.</p>
<p><em>Poder estadistico</em>: La probabilidad de rechazar la hipótesis contrastada cuando es falsa, es decir, cuando una hipótesis alternativa es verdadera; se denota como 1 – <span class="math inline">\(\beta\)</span>, donde beta es la probabilidad de cometer un error de tipo II.</p>
<p><em>Valor p</em>: El nivel de significancia en el cual el valor observado de la Prueba Estadística sería justamente significativo, es decir, caería justo en la región crítica.</p>
<p><a href="https://doi.org/10.1007/978-981-19-4411-6">Basic Concept of Hypothesis Testing and Parametric Test</a> In: Concept Building in Fisheries Data Analysis. Springer, Singapore.</p>
<p><a href="https://doi.org/10.1002/ece3.7365">When are hypotheses useful in ecology and evolution?</a></p>
<p><a href="https://doi.org/10.2307/3803199">Null Hypothesis Testing: Problems, Prevalence, and an Alternative</a></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Referencia: <a href="https://www.nature.com/articles/leu2016193">Gale, R. P., Hochhaus, A., &amp; Zhang, M. J. (2016). What is the (p-) value of the P-value?. Leukemia, 30(10), 1965-1967.</a></p>
<p>Los procesos inferenciales, incluidas las nociones de causa y efecto, están cada vez más dominados por los análisis estadísticos, un proceso en el que el concepto del valor P se ha vuelto central. Todo investigador científico cree que sabe qué es un valor P. Algunos pueden calcularlo por sí mismos; otros necesitan la ayuda de un estadístico o, a veces, de varios estadísticos para encontrar un valor P aceptable. ¿Por qué buscar entre diferentes opciones (comúnmente denominado P-hacking o «pesca de valor P»)? Porque sin un valor P estadísticamente significativo es difícil o imposible publicar tu investigación en una revista científica con un alto factor de impacto. (Más sobre los factores de impacto en un editorial posterior). Habitualmente, la significación estadística en este contexto se define como un valor P preestablecido &lt;0,05.</p>
<p>Curiosamente, y para nosotros algo alarmante, los estadísticos están menos seguros que los propios investigadores acerca de qué es exactamente un valor P, qué significa y qué implica sobre la reproducibilidad y replicabilidad de los datos científicos. Esto es completamente comprensible si consideramos la compleja historia del valor P.</p>
<p>El mérito de introducir el valor P en la investigación científica se le atribuye habitualmente al distinguido estadístico Fisher. Fisher definió el valor P como: «la probabilidad del resultado observado, junto con resultados más extremos, si la hipótesis nula fuera cierta». Es importante destacar, para lo que veremos después, que el valor P de Fisher no pretendía utilizarse de forma aislada, sino como una medida de inferencia estadística en el contexto del proceso más complejo de la inferencia científica.</p>
<p>El uso adecuado de la definición de Fisher del valor P requiere varios supuestos, entre ellos: que no exista relación entre el factor causal y el desenlace, que no haya errores sistemáticos —como clasificaciones erróneas o sesgos de confusión— y que se utilice la prueba estadística apropiada. Dados estos supuestos, es fácil entender por qué algunos investigadores piensan que el valor P indica la probabilidad de que la hipótesis nula sea cierta, o que un valor P alto indica que no hay asociación entre una variable y un desenlace. Como veremos, ambas ideas son incorrectas.</p>
<p>El siguiente avance en la interacción entre el pensamiento inferencial y la inferencia estadística llegó con Neyman y Pearson, quienes, a diferencia de Fisher, postularon una hipótesis alternativa formal y mutuamente excluyente respecto a la hipótesis nula, junto con un nivel de significación preelegido para rechazar la hipótesis nula. El enfoque de Neyman–Pearson estaba concebido como un análisis de toma de decisiones, mientras que el de Fisher no lo estaba.</p>
<p>La rigidez inherente al enfoque de Neyman–Pearson conlleva dos errores potenciales inevitables: rechazar la hipótesis nula cuando en realidad es verdadera (error de tipo I) y aceptar la hipótesis nula cuando en realidad es falsa (error de tipo II).</p>
<p>Es importante tener en cuenta que tanto el enfoque de Fisher como el de Neyman–Pearson son frecuentistas; ambos dejan de lado un tercer enfoque: el razonamiento inductivo bayesiano (que veremos más adelante).</p>
<p>Consideremos un ejemplo reciente del uso y abuso del valor P. Cuando los físicos descubrieron el bosón de Higgs, afirmaron que la solidez de los datos que lo respaldaban era de 5 sigma, lo que equivale a un valor P de 3 × 10⁻⁷, es decir, aproximadamente 1 en 3,5 millones. Contrario a lo que podrías pensar, esto no es la probabilidad de que el bosón de Higgs exista. Más bien, es la probabilidad de que, si el bosón de Higgs no existiera (la hipótesis nula), los datos experimentales obtenidos fueran al menos tan extremos como los observados. Dicho de otro modo, estos resultados ocurrirían solo en 1 de cada 3,5 millones de experimentos replicados. Tengamos en cuenta que el primer experimento podría ser el que arrojó ese resultado, y replicar el experimento 3,5 millones de veces más produciría resultados menos extremos. Este tipo de afirmación molesta a la mayoría de las personas interesadas en saber si el bosón de Higgs probablemente existe. Lo siento, pero de eso no trata el valor P. Además, cabe señalar que, a pesar del uso generalizado de P &lt; 0,05 o incluso P &lt; 0,01 como evidencia de significación estadística en la investigación biomédica, otras disciplinas científicas como la física de altas energías requieren valores P más bajos, de P &lt; 0,003 o incluso P &lt; 0,0000003, dependiendo de la novedad e importancia del hallazgo.</p>
<p>También vale la pena considerar los llamados eventos raros que ocurren cuando se realizan suficientes experimentos. Por ejemplo, si lanzas una moneda justa (con dos caras igualmente probables) 100 veces, es bastante improbable que obtengas 66 caras y 34 cruces. Sin embargo, si 1000 personas lanzan la misma moneda 100 veces cada una, algunas obtendrán más de 60 caras y menos de 40 cruces. Así que, incluso si un observador obtiene este resultado poco probable, se equivocaría al concluir que la moneda no es justa. Esta noción se conoce como el principio de improbabilidad y se aborda en otras publicaciones.</p>
<p>Otro punto a considerar es que el valor P no depende solo de los datos, sino también de cómo se analizaron. Por ejemplo, con exactamente los mismos datos, el valor P reportado será diferente según se hayan realizado 1, 2 o más análisis intermedios. Además, el enfoque del valor P debe considerar no solo los datos observados, sino también datos más extremos; de lo contrario, los valores P serían muy pequeños. Si lanzas una moneda justa 6 veces, la probabilidad de obtener 4 caras y 2 cruces es 0,23. Pero para probar la hipótesis nula (de que la moneda no está sesgada), debes sumar la probabilidad de 5 caras y 1 cruz (0,09) y la probabilidad de 6 caras y ninguna cruz (0,01) a la probabilidad de los datos reales. Por lo tanto, el valor P sería aproximadamente 0,33 y la hipótesis nula no se rechazaría.</p>
<p>Recientemente, la Asociación Estadounidense de Estadística publicó un informe sobre el valor P: «qué es, qué significa y cómo deben interpretarse los valores P». Este es un evento extraordinario, algo que la Asociación —la organización profesional de estadísticos más grande del mundo— nunca había hecho antes, lo que indica la importancia que ha adquirido este tema. La Asociación solicitó la opinión de estadísticos, muchos de ellos muy conocidos para los lectores de LEUKEMIA, como Donald Berry, Sander Greenland, John Ioannidis y Kenneth Rothman. El panel de expertos preparó y publicó un informe. Sería una tergiversación calificarlo como un documento de consenso, ya que a menudo no hay consenso. Nosotros interpretamos esta controversia de manera favorable porque el consenso implicaría un grado de acuerdo que el panel no alcanzó. Después de todo, citando a Michael Crichton: «Históricamente, el consenso ha sido el primer refugio de los sinvergüenzas. Es una forma de evitar el debate afirmando que el asunto está resuelto». ¿Lo dudan? Piensen en el consenso de que la Tierra es plana o de que la Tierra es el centro del universo. Ambos resultaron falsos a pesar del llamado consenso. Aunque la amenaza de excomunión era un buen incentivo para el consenso en el pasado (piensen en Galileo y Cardano), hoy en día es el temor de perder el vuelo del viernes por la tarde desde el aeropuerto de Dulles después de una conferencia de consenso de los Institutos Nacionales de Salud.</p>
<p>El tema que abordó la Asociación es el contexto, el proceso y el propósito del valor P. La cuestión surgió a raíz de una consulta del profesor George Cobb a la Asociación, quien preguntó (retóricamente): «(1) ¿por qué tantos colegios y escuelas de posgrado enseñan P = 0,05?; y (2) ¿por qué tantas personas siguen usando P = 0,05?». Las respuestas parecían ser «porque eso es lo que la comunidad científica y los editores de revistas quieren» y «porque eso es lo que se les enseñó a los estudiantes en la universidad o el posgrado». Estas explicaciones no son muy tranquilizadoras. Tampoco son nuevas estas preocupaciones. Las inquietudes sobre los usos y abusos de P &lt; 0,05 como base para rechazar la hipótesis nula se han descrito como con más fallos que la política de privacidad de Facebook. El mal uso de los valores P en la contrastación de hipótesis ha llevado a una crisis de reproducibilidad en la ciencia moderna y especialmente en la medicina clínica. Los lectores recordarán el estudio de científicos de Amgen, que no pudieron reproducir los resultados de 47 de 53 artículos emblemáticos sobre cáncer publicados en la literatura científica. Debido a esta controversia, algunas revistas han llegado incluso a prohibir el uso de valores P.</p>
<p>El informe del panel de la Asociación Estadounidense de Estadística señaló la noción de significación estadística que sustenta muchas conclusiones científicas, un concepto en el que la implicación de la significación estadística se deriva o infiere de un índice denominado valor P. Desafortunadamente, este índice se utiliza e interpreta de manera incorrecta con frecuencia. Citando su informe: «La validez de las conclusiones científicas, incluida su reproducibilidad, depende de algo más que los métodos estadísticos en sí mismos. Las técnicas apropiadamente elegidas, los análisis correctamente realizados y la interpretación adecuada de los resultados estadísticos también juegan un papel clave para garantizar que las conclusiones sean sólidas y que la incertidumbre que las rodea se represente correctamente».</p>
<p>Entonces, ¿qué dice el informe? Primero, define el valor P como la probabilidad bajo un modelo estadístico especificado de que un resumen estadístico de los datos sea igual o más extremo que los valores observados. Enfatizamos la noción de bajo un modelo estadístico especificado. Cuando calculamos un valor P, no estamos probando si la diferencia entre grupos o cohortes ocurrió por azar, sino la consistencia de los datos con un modelo estadístico propuesto. A menudo, el modelo estadístico que se prueba en ensayos clínicos es la llamada hipótesis nula. En consecuencia, cuando consideramos el valor P, debemos entender que no aborda si la hipótesis nula es cierta ni si el análisis estadístico de los resultados puede explicarse por el azar. Es decir, no proporciona una explicación de los resultados observados, sino qué tan bien se ajustan al modelo estadístico hipotetizado.</p>
<p>Otra consideración es que el valor P no refleja el tamaño del efecto. El informe afirma: «las conclusiones científicas y las decisiones comerciales o de política no deben basarse únicamente en si un valor P supera un umbral específico». Estamos de acuerdo. Efectos clínicamente poco importantes pueden tener valores P muy bajos cuando el tamaño de la muestra es grande, mientras que efectos clínicamente más importantes pueden tener valores P más altos debido a un tamaño de muestra pequeño. Los efectos clínicamente importantes estimados, con intervalos de confianza y valores P, deben reportarse de manera transparente. Por ejemplo, las razones de riesgo para eventos de tiempo hasta la ocurrencia pueden ser grandes y estadísticamente significativas incluso cuando el tamaño del efecto es pequeño. Por esta razón, también deben reportarse medidas basadas en tiempos de supervivencia media restringida.</p>
<p>Algunos estudios biomédicos seleccionan resultados con valores P &lt; 0,05 basándose en múltiples análisis de subgrupos, ignorando los pequeños tamaños de muestra en estos subgrupos. Los investigadores deberían reportar todos los análisis estadísticos realizados y todas las hipótesis probadas, para que el lector pueda considerar las tasas de falsos descubrimientos, que pueden ser necesarias cuando se realizan comparaciones múltiples. El informe no aborda la potencia (error tipo II), un aspecto importante al evaluar un valor P no estadísticamente significativo.</p>
<p>El panel enfatiza lo desaconsejable de centrarse en un punto arbitrario como P &lt; 0,05 para justificar afirmaciones científicas. Hay dos cuestiones aquí. Primero, considerar P = 0,05 como un punto para decidir la significación estadística es arbitrario y carece de una justificación matemática sensata. Segundo, hay otros factores que deben considerarse al evaluar si un resultado es estadísticamente significativo, como el diseño del estudio, la precisión de las mediciones, la evidencia externa al estudio, la exactitud de las mediciones y la validez de los supuestos subyacentes a los análisis de datos. Por ejemplo, un punto final de supervivencia suele ser más válido que un punto final de recaída de leucemia. Los autores afirman correctamente: «El uso generalizado de la significación estadística (generalmente aceptada como P &lt; 0,05) como licencia para hacer una afirmación de hallazgo científico (o verdad implícita) conduce a una considerable distorsión del proceso científico».</p>
<p>Estas consideraciones permanecen en el ámbito de los estadísticos frecuentistas. Aunque una discusión sobre el uso del razonamiento inductivo bayesiano con un espectro de probabilidades (como los límites de credibilidad) para expresar inferencia causal está fuera del alcance de nuestra discusión, también debería considerarse. Una revisión reciente de Kyriacou analiza el uso y las limitaciones del enfoque de inducción bayesiana. Las inferencias científicas basadas en el uso de métodos frecuentistas y bayesianos no son mutuamente excluyentes y a menudo son complementarias.</p>
<p>Otro problema es que los investigadores a menudo realizan múltiples análisis de sus datos, pero pueden presentar solo aquellos con un valor P estadísticamente significativo. Esto no permite al lector evaluar adecuadamente la validez de las afirmaciones y conclusiones de los investigadores ni considerar los posibles sesgos. Esta p-hacking (pesca de significación) es injusta, inapropiada y debe evitarse. La conclusión final es que el valor P, aisladamente, no puede ser utilizado para determinar si la hipótesis nula es correcta o no. Hay varias otras consideraciones importantes sobre el valor P que no se cubren en el informe de la Asociación, y remitimos a los lectores interesados a otras revisiones.</p>
<p>Aunque no planeamos ningún cambio inmediato en el proceso de revisión estadística para LEUKEMIA, es importante que los investigadores que envían artículos sigan las mejores prácticas estadísticas y reconozcan en sus análisis y discusiones las limitaciones del valor P para establecer inferencia causal.</p>
<p><strong>Ejemplo en ecología</strong></p>
<p>Imagina que un equipo de ecólogos quiere evaluar si la presencia de un depredador, el lobo (Canis lupus), afecta la densidad de población de una especie de ciervo en un área de bosque. Para ello, seleccionan 20 parcelas de bosque similares: en 10 parcelas los lobos están presentes, y en las otras 10 están ausentes. Miden la densidad de ciervos (número de individuos por kilómetro cuadrado) en cada parcela.</p>
<p>Hipótesis nula: No hay diferencia en la densidad de ciervos entre las parcelas con lobos y las parcelas sin lobos.</p>
<p>Hipótesis alternativa: Sí hay diferencia.</p>
<p>Supongamos que realizan una prueba estadística apropiada (por ejemplo, una prueba t de Student) y obtienen los siguientes resultados:</p>
<p>Densidad media en parcelas con lobos: 4.2 ciervos/km²</p>
<p>Densidad media en parcelas sin lobos: 7.8 ciervos/km²</p>
<p>Diferencia observada: 3.6 ciervos/km²</p>
<p>Valor P = 0.03</p>
<p>Interpretación correcta</p>
<p><em>“Si la hipótesis nula fuera cierta (es decir, si realmente no hubiera diferencia en la densidad de ciervos entre parcelas con y sin lobos), la probabilidad de obtener una diferencia de 3,6 ciervos/km² o más (en valor absoluto) entre los dos grupos sería de 0,03 (3 %).”</em></p>
<p>dicho de otra forma:</p>
<p><em>Bajo el supuesto de que los lobos no tienen ningún efecto sobre la densidad de ciervos, y asumiendo que el modelo estadístico es correcto (muestreo aleatorio, independencia, distribución adecuada, etc.), una diferencia tan grande como 3,6 ciervos/km² (o mayor) ocurriría solo en el 3 % de las repeticiones hipotéticas del experimento.</em></p>
<p>O, dicho de otra forma</p>
<p><em>“Si el experimento se repite 100 veces, y si la hipótesis nula fuera cierta (es decir, si realmente no hubiera diferencia en la densidad de ciervos entre parcelas con y sin lobos), una diferencia de 3,6 ciervos/km² o mayor se observaría solo en 3 de esas 100 repeticiones.”</em></p>
<p><a href="https://doi.org/10.1890/ES13-00160.1">Applied statistics in ecology: common pitfalls and simple solutions</a></p>
<p><a href="https://www.nature.com/articles/506150a">Scientific method: Statistical errors</a></p>
<p><a href="https://doi.org/10.1890/13-0590.1">In defense of P values</a></p>
<p><a href="https://www.jstor.org/stable/43495190">In defense of P values: comment on the statistical methods actually used by ecologists</a></p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Las dos subcategorías generales de la inferencia estadística son la estimación y el contraste de hipótesis.</p>
<p>Las distribuciones de probabilidad dependen frecuentemente de parámetros. Por ejemplo, si se conocen la media y la varianza de una distribución normal, es posible determinar las probabilidades de distintos eventos. En la práctica, sin embargo, estos parámetros son atributos de la población subyacente y, por lo tanto, son desconocidos. Nos enfrentamos entonces al problema de aprender todo lo posible sobre ellos a partir de la información contenida en una muestra aleatoria; es decir, debemos estimar su valor numérico.</p>
<p>Debido a la variabilidad muestral, no podemos afirmar que el valor del parámetro sea un número específico con certeza absoluta. Pero sí podemos hacer, en cierto sentido, una elección óptima basada en la información de la muestra y, a partir de ella, indicar un rango de valores dentro del cual confiamos que se encuentra el parámetro desconocido. Este tipo de inferencias corresponde a la categoría de estimación.</p>
<p>Un intervalo de confianza es un rango de valores, calculado a partir de los datos de una muestra, dentro del cual se estima que se encuentra el verdadero valor de un parámetro poblacional desconocido, con un cierto nivel de confianza.</p>
<p>Supongamos que en el estudio de los lobos y los ciervos, la diferencia media observada en densidad fue de 3.6 ciervos/km². Construimos un intervalo de confianza del 95 % y obtenemos:</p>
<p>Diferencia = 3.6 ciervos/km² (IC 95 %: 1.2 a 6.0)</p>
<p>Esto se interpreta de la siguiente manera:</p>
<p><em>“Con un 95 % de confianza, la verdadera diferencia en densidad de ciervos entre parcelas con y sin lobos se encuentra entre 1,2 y 6,0 ciervos/km².”</em></p>
<p><em>“Si tomáramos 100 muestras diferentes de la misma población y construyéramos un intervalo de confianza del 95 % para cada una, aproximadamente 95 de esos 100 intervalos contendrían el verdadero valor del parámetro poblacional.”</em></p>
<p><a href="https://doi.org/10.1016/S0378-1127(03)00331-1">A confidence interval approach to data analysis</a></p>
<p><a href="https://doi.org/10.1111/j.1469-185X.2007.00027.x">Effect size, confidence interval and statistical significance: a practical guide for biologists</a></p>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>En el contraste de hipótesis, tomamos una decisión (rechazar o no rechazar la hipótesis nula) basándonos en los datos de una muestra. Como trabajamos con muestras, existe la posibilidad de equivocarnos. Los errores tipo I y tipo II son las dos formas posibles de equivocarnos en esta decisión.</p>
<p><a href="https://doi.org/10.1016/S0022-0981(03)00304-6">Power, precaution, Type II error and sampling design in assessment of environmental impacts</a></p>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<p>El poder estadístico (o potencia) de un contraste de hipótesis es la capacidad que tiene un estudio para detectar un efecto real cuando ese efecto realmente existe.</p>
<p><a href="https://doi.org/10.1093/beheco/14.3.438">A survey of the statistical power of research in behavioral ecology and animal behavior</a></p>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HN%20Cursos%20publicidad/HN%20Biology%20Inv%20large.jpg" class="img-fluid figure-img"></p>
<figcaption>HN Biology Investigation Academy</figcaption>
</figure>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>